---
baseURL: "https://verhofste.tech"
languageCode: "en-gb"
defaultContentLanguage: "en"
title: "Jonas Verhofsté"
theme: "hermit"
rssLimit: 0

author:
  name: "Jonas Verhofsté"

params:
  dateform: "Jan 2, 2006"
  dateformShort: "Jan 2"
  dateformNum: "02-01-2006"
  dateformNumTime: "02-01-2006 15:04 +0100"

  homeSubtitle: "With great power comes great opportunity for confusion"
  bgImg: "background-optimized.jpg"
  customCSS:
    - "custom.css"
    - "forkawesome/css/fork-awesome.min.css"

  social:
    - name: "github"
      url: "https://github.com/JonasVerhofste"
    - name: "twitter"
      url: "https://twitter.com/JonasVerhofste"
    - name: "gnupg"
      url: "/jonasverhofste.asc"
    - name: "keybase"
      url: "https://keybase.io/jonasverhofste"
    - name: "envelope-o"
      title: "mail"
      url: "mailto:jonas@verhofste.tech"
